name: Gas Bot Emas

on:
  schedule:
    - cron: '0 1 * * *' # Berjalan otomatis jam 8 pagi WIB (1 UTC)
  workflow_dispatch:   # Tombol manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libs
        run: |
          pip install requests python-dotenv

      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOLD_API_KEY: ${{ secrets.GOLD_API_KEY }} # <-- Pastikan ini sama dengan di Settings
        run: python emas.py